// Code generated by goctl. DO NOT EDIT.
// Source: add.proto

package server

import (
	"context"

	"umbrella.github.com/go-zero-example/bookstore/rpc/add/add"
	"umbrella.github.com/go-zero-example/bookstore/rpc/add/internal/logic"
	"umbrella.github.com/go-zero-example/bookstore/rpc/add/internal/svc"
)

type AddServer struct {
	svcCtx *svc.ServiceContext
	add.UnimplementedAddServer
}

func NewAddServer(svcCtx *svc.ServiceContext) *AddServer {
	return &AddServer{
		svcCtx: svcCtx,
	}
}

func (s *AddServer) Ping(ctx context.Context, in *add.Request) (*add.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
