// Code generated by goctl. DO NOT EDIT.
// Source: check.proto

package server

import (
	"context"

	"umbrella.github.com/go-zero-example/bookstore/rpc/check/check"
	"umbrella.github.com/go-zero-example/bookstore/rpc/check/internal/logic"
	"umbrella.github.com/go-zero-example/bookstore/rpc/check/internal/svc"
)

type CheckServer struct {
	svcCtx *svc.ServiceContext
	check.UnimplementedCheckServer
}

func NewCheckServer(svcCtx *svc.ServiceContext) *CheckServer {
	return &CheckServer{
		svcCtx: svcCtx,
	}
}

func (s *CheckServer) Ping(ctx context.Context, in *check.Request) (*check.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
